FROM python:3.7-alpine
MAINTAINER Ewoud Werkman <ewoud.werkman@tno.nl> 

RUN apk add --update --no-cache g++ gcc libxslt-dev linux-headers musl-dev pcre pcre-dev zlib zlib-dev libressl-dev mailcap
RUN pip3.7 install --upgrade pip

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements-uwsgi.txt /usr/src/app/
RUN pip3.7 install -r requirements-uwsgi.txt

COPY . /usr/src/app

ENV PYTHONPATH=.:/usr/src/app
#ENV MAPEDITOR-TNO 1

EXPOSE 8111

CMD cd /usr/src/app && uwsgi uwsgi.ini 
