version: "3.3"

services:
  mapeditor:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: esdl-mapeditor:dev
    networks:
      - mapeditor-net
    volumes:
      - ..:/usr/src/app
    entrypoint: >
      watchmedo auto-restart
          --recursive
          --pattern="*.py;*.js"
          --directory="."
          --
    command: ["python", "app.py"]
    ports:
      - "${MAPEDITOR_PORT:-8111}:8111"
    env_file:
      - ../.env.open-source

networks:
  mapeditor-net:
    external:
      name: mapeditor-net
