version: "3.3"

services:
  mapeditor:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: 127.0.0.1:5000/mapeditor-dev
    volumes:
     - .:/usr/src/app
    entrypoint: >
      watchmedo auto-restart
          --recursive
          --pattern="*.py"
          --directory="."
          --
    command: ["python", "app.py"]
    ports:
      - 8111:8111

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    volumes:
      - usersettings_data:/data/db

volumes:
  usersettings_data: