FROM python:3.10-slim
MAINTAINER Ewoud Werkman <ewoud.werkman@tno.nl>
# Issues with PROJ and pyproj and Alpine linux: switch to debian base image. See https://pythonspeed.com/articles/alpine-docker-python/

#RUN apk add --update --no-cache g++ gcc libxslt-dev linux-headers musl-dev pcre pcre-dev zlib zlib-dev openssl-dev mailcap libffi-dev libffi
RUN apt-get -y update
RUN apt-get install -y gcc libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev curl
RUN pip install --upgrade pip

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements-gunicorn.txt /usr/src/app/
RUN pip install -r requirements-gunicorn.txt

COPY . /usr/src/app
ENV PYTHONPATH=.:/usr/src/app

EXPOSE 8111

CMD cd /usr/src/app && gunicorn --log-level debug --name mapeditor -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --threads 32 app:app -b :8111
