version: "3.3"

services:
  mapeditor:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: esdl-mapeditor:dev
    networks:
      - mapeditor-net
    volumes:
      - ..:/usr/src/app
    entrypoint: >
      watchmedo auto-restart
          --recursive
          --pattern="*.py"
          --directory="."
          --
    command: ["python", "-u", "app.py"]
    ports:
      - "${MAPEDITOR_PORT:-8111}:8111"
    env_file:
      - ../.env
    environment:
      - OIDC_CLIENT_SECRETS=credentials/client_secrets_local-docker.json

  vue-watch:
    image: node:14-slim
    working_dir: /usr/src/app
    volumes:
      - ..:/usr/src/app
    command: ["yarn", "run", "watch"]
    environment:
      - NODE_ENV=development

networks:
  mapeditor-net:
    external:
      name: mapeditor-net
